### ISSUE TITLE
no alternative certificate subject name matches target host name 'hello-mtls.default.svc.cluster.local'

### ISSUE THREAD

**Issue by JackSinclairT** [smallstep/autocert#34]
### Subject of the issue
When following the steps to setup autocert for the hello-mtls server and hello-mtls-client pods, the following error occurs on the hello-mtls client pod:

"no alternative certificate subject name matches target host name 'hello-mtls.default.svc.cluster.local'"

The same occurs when curling manually via kubectl exec on the hello-mtls-client pod.
curl -sS \
       --cacert /var/run/autocert.step.sm/root.crt \
       --cert /var/run/autocert.step.sm/site.crt \
       --key /var/run/autocert.step.sm/site.key \
       https://hello-mtls.default.svc.cluster.local

Is this down to lack of support for AKS perhaps?

### Environment
* Kubernetes version: v1.18.14
* Cloud provider or hardware configuration: Azure Kubernetes Service
* OS (e.g., from /etc/os-release): Ubuntu 18.04
* Install tools: helm

### Steps to reproduce
Followed the helm install steps here
https://artifacthub.io/packages/helm/smallstep/autocert

And the annotate pods steps here
https://github.com/smallstep/autocert#annotate-pods-to-get-certificates

And the hello mtls steps here
https://github.com/smallstep/autocert#hello-mtls

### Expected behaviour
The following should be logged in the hello-mtls-client pod:
Hello, hello-mtls-client.default.pod.cluster.local!

### Actual behaviour
the hello-mtls-client pod logs the following error:
"no alternative certificate subject name matches target host name 'hello-mtls.default.svc.cluster.local'"

### Additional context
Add any other context about the problem here

**Comment by maraino** [comment]
@JackSinclairT I'm not sure right now, but I believe this error was introduced by a PR that we accepted, and later noticed it had that error. We fixed it a month ago but we never create a release. 

I'll make sure this is fixed and generate a new release.

**Comment by maraino** [comment]
@JackSinclairT this should be fixed by updating the image to 0.15.0 or using the chart 1.15.0

**Comment by thestupendous** [comment]
I am still facing this issue. I tried using 0.15.0 image, but it still is giving the same error.
